Abort if board has no RAM free

diff --git a/install b/install
--- a/install
+++ b/install
@@ -84,6 +84,17 @@ gamememMIN=$((($mem * 80/100) - 1024)) # Figure a MINIMUM amount of memory to al
 oc_volt=0
 oc_friendly="N/A - You'll need to overclock manually"
 
+if (( $gamememMIN < 0 )); then
+  echo "||| YOU HAVE NO RAM |||"
+  echo
+  echo "Either you have other things running, or your board"
+  echo "is simply not good enough to run a Minecraft server."
+  echo
+  echo "Aborting."
+  echo
+  exit 1
+fi
+
 if [[ "$revision" == *"b03111" ]] ||
    [[ "$revision" == *"b03112" ]] ||
    [[ "$revision" == *"c03111" ]] ||
