Fixes, add remove and replace feature

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,7 +6,7 @@
 
 # Corresponding video series: https://category5.tv/feature/minecraft
 
-pcver="2.4"
+pcver="2.5"
 
 if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root" 2>&1
@@ -222,76 +222,6 @@ else
   exit 1
 fi
 
-exec 3>&1
-result=$(dialog --title "Pinecraft $pcver" \
-         --menu "Choose your game seed:" 20 40 10 \
-         "A"       "Random (Default)" \
-         "B"       "Custom" \
-         "C"       "Category5 TV RPi Server" \
-         "D"       "Minecraft Title Screen" \
-         "E"       "Slime Farm" \
-         "F"       "Obsidian Farm" \
-         "G"       "Woodland Mansion" \
-         "H"       "Triple Island Ocean Monument" \
-         "I"       "Spruce Village and Coral Reef" \
-         "J"       "Shipwreck Village" \
-         "K"       "Underwater Temple" \
-         "L"       "Diamond Paradise" \
-       2>&1 1>&3);
-
-if [[ $? == 0 ]]; then
-  case $result in
-    A)
-      seed=""
-      ;;
-    B)
-      seed="custom"
-      ;;
-    C)
-      seed="-4385290424787160722"
-      ;;
-    D)
-      seed="2151901553968352745"
-      ;;
-    E)
-      seed="7000"
-      ;;
-    F)
-      seed="-8880302588844065321"
-      ;;
-    G)
-      seed="throwlow"
-      ;;
-    H)
-      seed="6073041046072376055"
-      ;;
-    I)
-      seed="673900667"
-      ;;
-    J)
-      seed="-613756530319979507"
-      ;;
-    K)
-      seed="-5181140359215069925"
-      ;;
-    L)
-      seed="1785852800490497919"
-      ;;
-    esac
-else
-  echo
-  echo
-  echo "Aborted."
-  echo
-  exit 1
-fi
-
-# Input custom seed
-if [[ $seed == "custom" ]]; then
-  seed=$(dialog --stdout --title "Custom World Seed" \
-    --inputbox "Enter your custom world seed" 8 50)
-fi
-
 # Username may be provided on CLI as in 1.0
 user=$1
 
@@ -349,6 +279,7 @@ dialog --title "End-User License Agreement"  --yesno "In order to proceed, you m
 instdir="/home/$user/minecraft/"
 
 upgrade=0
+replace=0
 if [[ -e /home/$user ]]; then
   if [[ -e ${instdir} ]]; then
     if [[ ! -e ${instdir}cat5tv.ver ]]; then
@@ -356,17 +287,39 @@ if [[ -e /home/$user ]]; then
         --msgbox "\n${instdir} already exists, but is not created by Pinecraft.\n\nPlease move or remove the folder and try again." 11 50
       exit 0
     else
-      dialog --title "Upgrade"  --yesno "\nPinecraft is already installed. Upgrade?" 8 40
-      case $? in
-      1)
-       echo
-       echo
-       echo "Aborted"
-       echo
-       exit 1 ;;
-      esac
 
-      upgrade=1
+      exec 3>&1
+      result=$(dialog --title "Pinecraft $pcver" \
+         --menu "Pinecraft is already installed:" 9 40 4 \
+         "U"       "Upgrade Software (Keep World)" \
+         "R"       "Remove Previous and Reinstall" \
+        2>&1 1>&3);
+
+      if [[ $? == 0 ]]; then
+        case $result in
+          U)
+            upgrade=1
+            ;;
+          R)
+            dialog --title "Confirmation"  --yesno "\nThis will remove your entire previous installation, including your world files.\n\nContinue?" 12 50
+            case $? in
+              1)
+              echo
+              echo
+              echo "Aborted."
+              echo
+              exit 1 ;;
+            esac
+            replace=1
+            ;;
+          esac
+        else
+          echo
+          echo
+          echo "Aborted."
+          echo
+          exit 1
+        fi
 
     fi
   fi
@@ -374,6 +327,81 @@ else
   echo "Aborting: $user does not have a homedir."
   exit 1
 fi
+
+# Get the level seed, but only if this is a new install
+if [[ $upgrade == 0 ]]; then
+  exec 3>&1
+  result=$(dialog --title "Pinecraft $pcver" \
+         --menu "Choose your game seed:" 20 40 10 \
+         "A"       "Random (Default)" \
+         "B"       "Custom" \
+         "C"       "Category5 TV RPi Server" \
+         "D"       "Minecraft Title Screen" \
+         "E"       "Slime Farm" \
+         "F"       "Obsidian Farm" \
+         "G"       "Woodland Mansion" \
+         "H"       "Triple Island Ocean Monument" \
+         "I"       "Spruce Village and Coral Reef" \
+         "J"       "Shipwreck Village" \
+         "K"       "Underwater Temple" \
+         "L"       "Diamond Paradise" \
+       2>&1 1>&3);
+
+  if [[ $? == 0 ]]; then
+    case $result in
+    A)
+      seed=""
+      ;;
+    B)
+      seed="custom"
+      ;;
+    C)
+      seed="-4385290424787160722"
+      ;;
+    D)
+      seed="2151901553968352745"
+      ;;
+    E)
+      seed="7000"
+      ;;
+    F)
+      seed="-8880302588844065321"
+      ;;
+    G)
+      seed="throwlow"
+      ;;
+    H)
+      seed="6073041046072376055"
+      ;;
+    I)
+      seed="673900667"
+      ;;
+    J)
+      seed="-613756530319979507"
+      ;;
+    K)
+      seed="-5181140359215069925"
+      ;;
+    L)
+      seed="1785852800490497919"
+      ;;
+    esac
+  else
+    echo
+    echo
+    echo "Aborted."
+    echo
+    exit 1
+  fi
+
+  # Input custom seed
+  if [[ $seed == "custom" ]]; then
+    seed=$(dialog --stdout --title "Custom World Seed" \
+      --inputbox "Enter your custom world seed" 8 50)
+  fi
+
+fi
+
 
 # Gather some info about your system which will be used to determine the config
 revision=$(cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}')
@@ -503,6 +531,20 @@ dialog --title "Pinecraft $pcver"  --yesno "Automatically load the server on boo
 #   ;;
 #  esac
 
+if [[ $upgrade == 1 ]] || [[ $replace == 1 ]]; then
+  if [[ -e ${instdir}stop ]]; then
+    dialog --infobox "Stopping server..." 3 22 ;
+    ${instdir}stop > /dev/null 2>&1
+  fi
+fi
+if [[ $replace == 1 ]]; then
+  dialog --infobox "Creating Backup in home folder..." 3 40 ;
+  tar -czvf ${instdir}../pinecraft_backup-$(date -d "today" +"%Y-%m-%d-%H-%M").tar.gz $instdir > /dev/null 2>&1
+  cd ${instdir}..
+  dialog --infobox "Removing Old Install..." 3 27 ;
+  rm -rf ${instdir}
+  sleep 2
+fi
 
 if [[ $upgrade == 0 ]]; then
   mkdir $instdir
@@ -662,10 +704,13 @@ else
   echo "exec java -Xms${gamememMIN}M -Xmx${gamemem}M -jar `basename $jarfile` --nogui" >> ${instdir}server
 fi
 chmod +x ${instdir}server
+# Set ownership to the user
+chown -R $user:$user $instdir
 # Need to generate the config and EULA
+# Note: Because the EULA is not yet accepted within eula.txt, the server will init and quit immediately.
 if [[ $upgrade == 0 ]] || [[ ! -e ${instdir}server.properties ]]; then
   dialog --infobox "Initializing server..." 3 34 ; sleep 1
-  ${instdir}server > /dev/null 2>&1
+  su - $user -c ${instdir}server > /dev/null 2>&1
 fi
 if [[ $eula == "accepted" ]]; then
   echo "# https://account.mojang.com/documents/minecraft_eula ACCEPTED by user during installation
@@ -760,11 +805,11 @@ if [[ -e ${instdir}server.properties ]]; then
   if [[ $upgrade == 0 ]]; then
     /bin/sed -i '/difficulty=/c\difficulty=normal' ${instdir}server.properties
     /bin/sed -i '/view-distance=/c\view-distance=7' ${instdir}server.properties
+    /bin/sed -i "/level-seed=/c\level-seed=${seed}" ${instdir}server.properties
   fi
 
   # These ones, however, are selected by the user, so we'll make these changes even if already installed
   /bin/sed -i "/gamemode=/c\gamemode=${gamemode}" ${instdir}server.properties
-  /bin/sed -i "/level-seed=/c\level-seed=${seed}" ${instdir}server.properties
 
 fi
 
