Add level-type option

diff --git a/install b/install
--- a/install
+++ b/install
@@ -659,6 +659,42 @@ fi
 
 exec 3>&1
 result=$(dialog --title "Pinecraft Installer $pcver $mcver" \
+         --menu "Choose your level type:" 20 40 10 \
+         "N"       "Normal (Default)" \
+         "F"       "Super Flat" \
+         "L"       "Large Biomes" \
+         "A"       "Amplified" \
+         "S"       "Single Biome Surface" \
+       2>&1 1>&3);
+
+if [[ $? == 0 ]]; then
+  case $result in
+    N)
+      leveltype="normal"
+      ;;
+    F)
+      leveltype="flat"
+      ;;
+    L)
+      leveltype="large_biomes"
+      ;;
+    A)
+      leveltype="amplified"
+      ;;
+    S)
+      leveltype="single_biome_surface"
+      ;;
+    esac
+else
+  echo
+  echo
+  echo "Aborted."
+  echo
+  exit 1
+fi
+
+exec 3>&1
+result=$(dialog --title "Pinecraft Installer $pcver $mcver" \
          --menu "Choose your game type:" 20 40 10 \
          "S"       "Survival" \
          "C"       "Creative" \
@@ -844,7 +880,7 @@ Server User:
 $user
 
 Server Version:
-$flavor $mcver ($gamemode)" 20 50
+$flavor $mcver ($leveltype $gamemode)" 20 50
 
 if [[ ! $oc_freq == 0 ]]; then
   dialog --title "Confirmation"  --yesno "\nI will be modifying ${configfile} to overclock this ${board}. I am not responsible for damage to your system, and you do this at your own risk.\n\nContinue?" 12 50
@@ -1318,6 +1354,14 @@ if [[ -e ${instdir}server.properties ]]; then
       # Add it if it doesn't exist
       if ! grep -q "gamemode=" ${instdir}server.properties; then
         echo "gamemode=${gamemode}" >> ${instdir}server.properties
+      fi
+
+    # Level Type (User Selected During Install)
+      # Change the value if it exists
+      /bin/sed -i "/level-type=/c\level-type=minecraft:${leveltype}" ${instdir}server.properties
+      # Add it if it doesn't exist
+      if ! grep -q "level-type=minecraft:" ${instdir}server.properties; then
+        echo "level-type=minecraft:${leveltype}" >> ${instdir}server.properties
       fi
 
 fi
